version: '3.3'

services:
  app:
    image: ${IMAGE:-pipdevs/app}
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - HTTP_ENABLED=true
      - GRPC_ENABLED=true
      - EMAIL_DISABLED=true
    ports:
      - "8080:8080"
      - "8090:8090"
