---
# Container descriptor
- descriptor: "pip-services:context-info:default:default:1.0"
  name: "service-email"
  description: "Email delivery microservice for pip-services"

# Console logger
- descriptor: "pip-services:logger:console:default:1.0"
  level: "trace"

# Performance counters that posts values to log
- descriptor: "pip-services:counters:log:default:1.0"
  level: "trace"

# Default controller
- descriptor: "service-email:controller:default:default:1.0"
  connection:
    host: "{{{EMAIL_SERVICE_HOST}}}"
    ssl: "{{{EMAIL_SSL}}}"
    port: "{{{EMAIL_SERVICE_PORT}}}"
  credential:
    username: "{{{EMAIL_USER}}}"
    password: "{{{EMAIL_PASS}}}"
  message:
    from: "{{{EMAIL_FROM}}}"
  parameters:
    client_name: "{{{CLIENT_NAME}}}"
    client_url: "{{{CLIENT_URL}}}"
    server_url: "{{{SERVER_URL}}}"
    signature: "{{{EMAIL_SIGNATURE}}}"
  options:
    disabled: {{{EMAIL_DISABLED}}}
# - descriptor: "service-email:controller:default:default:1.0"
#   connection:
#     service: Gmail
#     host: host233.hostmonster.com
#     ssl: "true"
#     port: "465"
#   credential:
#     username: "info@iquipsys.com"
#     password: "iQuipsys#01"
#   message:
#     from: positron@iquipsys.com
#   parameters:
#     client_name: iQuipsys Positron
#     client_url: http://www.positron.iquipsys.net
#     server_url: api.positron.iquipsys.net
#     signature: Yours iQuipsys support


{{#if HTTP_ENABLED}}
# Common HTTP endpoint
- descriptor: "pip-services:endpoint:http:default:1.0"
  connection:
    protocol: "http"
    host: "0.0.0.0"
    port: 8080

# HTTP endpoint version 1.0
- descriptor: "service-email:service:http:default:1.0"
  swagger:
    enable: true
    auto: true

# Heartbeat service
- descriptor: "pip-services:heartbeat-service:http:default:1.0"

# Status service
- descriptor: "pip-services:status-service:http:default:1.0"

# Swagger service
- descriptor: "pip-services:swagger-service:http:default:1.0"
{{/if}}

{{#if GRPC_ENABLED}}
# Common GRPC endpoint
- descriptor: "pip-services:endpoint:grpc:default:1.0"
  connection:
    protocol: "http"
    host: "0.0.0.0"
    port: 8090

# GRPC endpoint version 1.0
- descriptor: "service-email:service:grpc:default:1.0"

# Commandable GRPC endpoint version 1.0
- descriptor: "service-email:service:commandable-grpc:default:1.0"
{{/if}}
